enum BackgroundColorClass {
  BackgroundOverlay = "backgroundColorBackgroundOverlay",
  Dimmer = "backgroundColorDimmer",
  Error = "backgroundColorError",
  Green = "backgroundColorGreen",
  Ghost = "backgroundColorGhost",
  LightBlue = "backgroundColorLightBlue",
  LightPink = "backgroundColorLightPink",
  LightPurple = "backgroundColorLightPurple",
  LightPurpleHover = "backgroundColorLightPurpleHover",
  Navy = "backgroundColorNavy",
  NavyHover = "backgroundColorNavyHover",
  Pink = "backgroundColorPink",
  Primary = "backgroundColorPrimary",
  Purple = "backgroundColorPurple",
  Red = "backgroundColorRed",
  RedHover = "backgroundColorRedHover",
  Secondary = "backgroundColorSecondary",
  Tertiary = "backgroundColorTertiary",
  TwitterBlue = "backgroundColorTwitterBlue",
  White = "backgroundColorWhite",
  Yellow = "backgroundColorYellow",
}

export default BackgroundColorClass;
